### ISSUE TITLE
Hide “Backend Admin” and “Admin Dashboard” links from the interface of “End Users”

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#10]
Hide “Backend Admin” and “Admin Dashboard” links from the interface of “End Users”

<img width="1680" alt="Screen Shot 2020-05-20 at 2 38 23 PM" src="https://user-images.githubusercontent.com/50957748/82413455-f0e55a00-9aa7-11ea-9896-b8712c6c6517.png">

**Comment by luna404** [comment]
This has been added to the backlog of enhancement request and will be implemented when ready.

**Comment by luna404** [comment]
No longer relevant
