### ISSUE TITLE
Arabic Interface (Data Entry & Visualization)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#11]
There should be an Arabic Interface (icons, buttons) in the platform wherein an end-user can select which language he/she prefers as well as the texts (e.g., titles and legends of graphs/maps) in the dashboards.

**Comment by luna404** [comment]
A multi-language interface for the HeRAMS platform is in the development plan for 2020 and should be coming in the near future.

**Comment by JeffDotingco** [comment]
Just click your account name in the platform to change the language:

<img width="1680" alt="Screen Shot 2020-06-22 at 6 19 32 PM" src="https://user-images.githubusercontent.com/50957748/85276793-f4a83a00-b4b4-11ea-9cd6-5d896daf3a2e.png">

**Comment by JeffDotingco** [comment]
First version of the Arabic interface already released

**Comment by luna404** [comment]
As the multilingual interface has been successfully released, I will close this issue. If there are any issues (e.g. missing or wrong translations) please create a new issue.
