### ISSUE TITLE
Auto-fill Functionality and Accessibility Fields

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#12]
Auto-fill Functionality and Accessibility Fields:

- When CONDB=="Fully damaged / A3", HFFUNCT is automatically filled as "Non-functioning / A3" as well as HFACC as "Non-functioning". 

- When HFFUNCT=="Non-functioning / A3", HFACC is automatically set at "Non-functioning"

**Comment by luna404** [comment]
From my point of view this is not a data collection issue but rather an issue related to data analysis and interpretation.  @MustafaAbdulrahmanWHO or @JeffDotingco could you give some background to this issue.

The only place where I see this as an issue is the dashboards where "non-functioning" and "inaccessible" health facilities are being shown as "unknown". This is something that will be corrected as part of a wider revision of the project dashboards in the coming months.  
For any analysis that is produced outside of HeRAMS, this requires proper training of users to make sure they fully understand the survey logic.
