### ISSUE TITLE
Improving Visualization (district-level analysis & drill-down)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#13]
Improving Visualization (district-level analysis & drill-down)

**Comment by JeffDotingco** [comment]
@ALKHSHBI, if this issue is related to the attached screenshot from your email, the issue in the map has already been fixed. 

<img width="960" alt="Kuhlan Affar Analysis" src="https://user-images.githubusercontent.com/50957748/82423734-c949be00-9ab6-11ea-876e-b63d69c8cad4.png">

**Comment by luna404** [comment]
@JeffDotingco please label resolved issue appropriately and close them.

**Comment by JeffDotingco** [comment]
@luna404, I don't have access to labels.:)

**Comment by MustafaAbdulrahmanWHO** [comment]
Dear Colleagues, please note that the map is not working properly (see screenshot)

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco, Dear Jeff, please note that the map is not working properly (see screenshot)

**Comment by JeffDotingco** [comment]
That's the reason @MustafaAbdulrahmanWHO why I asked if this issue is related to health facility locations not being shown in the map for confirmation. Indeed, the health facility locations were not shown before if you update them because the coordinates were linked to the GPS equation / text display (MoSDGPS_SQ001 and MoSDGPS_SQ002 variables for HF locations to be shown, but being linked to  MoSDGPS_SQ001_EQ and MoSDGPS_SQ001_EQ; blank: thus not shown in the map).  I have already changed the codes as Latitudes and Longitudes for the equation columns. Please kindly check district-level dashboards

**Comment by MustafaAbdulrahmanWHO** [comment]
@luna404 Dear Caroline . . Could you please keep this issue open till we meet as agreed and discuss the available visualization in the platform and the features and indicators that need to be added/updated.
