### ISSUE TITLE
Missing Fields in Frontend Export

### ISSUE THREAD

**Issue by MustafaAbdulrahmanWHO** [HeRAMS-WHO/herams-support#14]
**### Urgency: High**
**Describe the bug** 
@SamuelPetragallo @JeffDotingco @luna404 @SamMousa 
Recently Filled Geographical Coordinates (i.e. Longitude and Latitude) are not available in Frontend Export though are available in Backend Export.

**Brief description**
I have recently filled the missing geographical coordinates of some HFs (91 HFs) through the Backend Admin. However, when exporting the data from Frontend those recently filled geographical coordinates are not displayed in the main fields of "Longitude" and "Latitude" though they appear in Backend Export.

**Steps to reproduce the issue**
1. Go to 'Projects'
2. Scroll down to   'Yemen'
3. Click on  'Download' which is the "Down Arrow Button"
4. See error (No "Longitude" nor "Latitude" appears in main fields of Longitude and Latitude for any recently filled geographical coordinates whose geographical coordinates were missing (though they appear in Backend Export).

**Expected behavior**
I expect the recently filled geographical coordinates (i.e. Longitude and Latitude) to appear in the main fields of "Longitude" and "Latitude" in the Frontend Export.

**Additional details**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.
<img width="904" alt="Longitude and Latitude not available in Frontend Export - Highlighted in Red" src="https://user-images.githubusercontent.com/65541276/84770846-03887b80-afe1-11ea-9357-25f8b11ead59.PNG">
<img width="589" alt="Longitude and Latitude available in Backend Export - Highlighted in Yellow" src="https://user-images.githubusercontent.com/65541276/84770854-071c0280-afe1-11ea-962e-89b16187c6fe.PNG">

**Comment by JeffDotingco** [comment]
Hi @MustafaAbdulrahmanWHO thanks for raising this issue, @SamMousa is already looking into this.

**Comment by JeffDotingco** [comment]
Hi @MustafaAbdulrahmanWHO, kindly double check. Sam Mousa already fixed this issue and I have also tested this. The issue on missing GPS coordinates seems to be resolved upon testing.
