### ISSUE TITLE
Remove Duplicate and Non-Essential Fields/Columns

### ISSUE THREAD

**Issue by MustafaAbdulrahmanWHO** [HeRAMS-WHO/herams-support#18]
**### Urgency: High**
**Describe the Bug** 
@SamuelPetragallo @JeffDotingco @luna404 @SamMousa 
Remove any duplicate and/or useless columns unless there is an urgent need for (e.g. duplicate geographical coordinates, Governorate/District, HF-ID, etc.).

**Brief description**
There are several duplicates and/or useless fields/columns that have been created/added recently and almost all of those new added/created fields/columns are not essential parts of the Standard Data Model and some of them were just created to perform secondary (or go around) tasks which are not of significant influence and could be removed.

**Steps to reproduce the issue**
1. Go to 'Projects'
2. Scroll down to   'Yemen'
3. Click on 'Download' which is the "Down Arrow Button"
4. See error: Duplicated and/or useless fields or columns (i.e. samples of a set of duplicated/useless columns are highlighted using a unique color for each set of duplicated/useless fields or columns)

**Expected behavior**
The Desired Action is to reduce the number of new and/or duplicated columns as much as possible in order to minimize the difference between the HeRAMS 2018 & HeRAMS 2020 datasets structure & Keep only essential fields/columns as per the Standard Data Model as well as new fields/columns which are urgently required.

**Additional details**
The below screenshot and the attached file show samples of the duplicated/useless fields or columns (p.s. all columns highlighted in “Yellow” are duplicates of “Governorate and/or District” & columns highlighted in “Orange” are duplicates of “HF-ID” & columns highlighted in “Pink” are duplicates of “Geographical Coordinates”, etc.):

<img width="939" alt="Duplicate or useless Columns - Highlighted" src="https://user-images.githubusercontent.com/65541276/85934720-c9c44880-b8ef-11ea-886f-5ef754415053.PNG">

[Duplicate or useless Columns - Highlighted.xlsx](https://github.com/HeRAMS-WHO/herams-support/files/4841472/Duplicate.or.useless.Columns.-.Highlighted.xlsx)

Labels
Type: Bug
Urgency: High
Subject: Data Collection

**Comment by JeffDotingco** [comment]
related to duplication of some columns & blank columns issue #7, kindly check the table describing the added columns and reasons of having additional columns in the dataset @MustafaAbdulrahmanWHO

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco Dear Jeff, please be informed that in the case of Columns that are not essential and their only purpose is to be displayed only in the questionnaire (uneditable) such as GEO3, GEO6, GPS coordinates, etc. then such columns should be removed (except for "Health Facility Name in Arabic" field which is required to remind the enumerator what health facility he/she is currently updating).

**Comment by JeffDotingco** [comment]
@MustafaAbdulrahmanWHO, please be also informed that I am on contract break and will be working for WPRO starting this week. I will sort the needed highly urgent request of this issue in the coming days as I am also busy supporting MOH for the COVID-19 response while on contract break.

**Comment by JeffDotingco** [comment]
Also kindly don't include mentioning Sam Mousa for future issues. Rest assured that we always notify him whenever issues raised involve his support. For support that need his support, we put a label status: under-review if he is already into it and change it accordingly if he has already resolved the issue.

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco Hi Jeff, I noticed that you have closed this issue. So, does this mean that you have already removed all duplicate/useless/blank columns and kept only the essential columns/fields and that the current HeRAMS Data Structure is Final? Please confirm so that we prepare our dynamic analysis based on the last updated HeRAMS data structure and that no further changes will happen on the HeRAMS data structure. Thank you in advance and wish you all the best.

**Comment by JeffDotingco** [comment]
> @JeffDotingco Hi Jeff, I noticed that you have closed this issue. So, does this mean that you have already removed all duplicate/useless/blank columns and kept only the essential columns/fields and that the current HeRAMS Data Structure is Final? Please confirm so that we prepare our dynamic analysis based on the last updated HeRAMS data structure and that no further changes will happen on the HeRAMS data structure. Thank you in advance and wish you all the best.
I confirm. Added a label status:implemented
