### ISSUE TITLE
Login Problem - Unable to Access My Account  on (herams.org)

### ISSUE THREAD

**Issue by MustafaAbdulrahmanWHO** [HeRAMS-WHO/herams-support#19]
**Describe the bug**
@SamuelPetragallo @JeffDotingco @luna404 
I couldn’t access any of my accounts on the new herams.org platform (i.e. neither my Admin Account nor an End-User Account).

**Brief description**
Please be informed that today I couldn’t access any of my accounts on the new herams.org platform (i.e. neither my Admin Account nor any End-User Account).
When I tried to access my Admin Account, I wasn’t navigated at all though I’ve filled my credentials as usual. However, when I tried to access my End-User Account the following Error Message appeared “Unable to verify your data submission”.

**Steps to reproduce the issue**
1. Go to (herams.org)
2. Fill your credentials
3. Click on “Login”
4. See error message for Non-Admin accounts: “Unable to verify your data submission” & when logging using your Admin Account, there is no No navigation at all

**Expected behavior**
The Desired Action is to solve this Login problem so that all users can access their accounts (including Admin Users).

**Additional details**

![Login Error Problem - Unable to Access My Account - Whole Screen](https://user-images.githubusercontent.com/65541276/89697046-105f8680-d923-11ea-84f8-0a0cf4d8ab09.jpg)

**Comment by luna404** [comment]
This has been resolved
