### ISSUE TITLE
Scrolling problem of the platform 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#5]
Issue with scrolling in the platform especially on the online questionnaire wherein the user has to scroll the down to the bottom of the screen just to press "Next" in the questionnaire

**Comment by JeffDotingco** [comment]
Scrolling issue seems to be fixed now.

<img width="1680" alt="Screen Shot 2020-05-19 at 11 14 37 PM" src="https://user-images.githubusercontent.com/50957748/82344416-9c4dca80-9a26-11ea-9206-9822affd1f5c.png">

**Comment by luna404** [comment]
Please close issues that have been resolved
