### ISSUE TITLE
Issue on frontend data exporting (xlsx) 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#6]
There is an issue on frontend excel data exporting wherein it can't be opened when you enable "TEXT HEADER", enable "ANSWERS AS TEXT" and enable Arabic as the language. However, the downloaded file can be opened in excel if you disable "TEXT HEADER" and "ANSWERS AS TEXT"

**Comment by MustafaAbdulrahmanWHO** [comment]
This is related to "CSV" export from Frontend

**Comment by luna404** [comment]
@MustafaAbdulrahmanWHO the issue you are experiencing with the CSV export is a problem with Excel misreading the data. For this reason we are working on improving the Excel export. An improved version of the Excel export will be release with our next release. Once this has been release we recommend that for languages other than English, data is download as Excel.

**Comment by JeffDotingco** [comment]
Improved version of frontend data exporting through excel already implemented.
