### ISSUE TITLE
Duplication of some columns & blank columns

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-support#7]
Duplication of some columns & blank columns (at least Highlight changed/new Columns in both HeRAMS 2018 & 2020 database)

**Comment by JeffDotingco** [comment]
| 2020 HeRAMS question code|  2020 HeRAMS question code description | 2018 HeRAMS equivalent question code | Reason for adding in 2020 HeRAMS | 
|--------|----------| --------- |------- |
|GEO1 |Governorate / District answers as single-choice |   | Implemented for filtering to work in the dashboard |
|GEO2 |Governorate as single-choice |  |Implemented for governorate filtering to work in the dashboard  |
|GEO3 |Governorate as short free text |  GEO01 |  |
|GEO4 |Governorate PCODE |  | |
|GEO5 |District as single-choice |  |Implemented for district filtering to work in the dashboard  |
|GEO6 |District as short free text  | GEO02 | |
|GEO7 |District PCODE  | | |
|GEO3EQ |Equation to mirror answer in GEO3 **(blank answer in dataset if HF record is not yet updated, duplicate answer with GEO3 if HF record is updated)**||Needed variable for Text Display (Requested for Governorates / District to be shown only to end users and uneditable)| 
|GEO6EQ|Equation to mirror answer in GEO6 **(blank answer in dataset if HF record is not yet updated, duplicate answer with GEO6 if HF record is updated)**||Needed variable for Text Display (Requested for Governorates / District to be shown only to end users and uneditable)|
|PoSDTEXT|Text display of Governorates and Districts through GEO3EQ & GEO6EQ **(blank answer in dataset)** ||Text Display for Governorates and Districts to be shown only to end users and uneditable as requested| 
|Latitude|Equation to mirror answer in MoSDGPS_SQ001 **(blank answer in dataset if HF record is not yet updated, duplicate answer with MoSDGPS_SQ001 if HF record is updated)**||Needed variable for text display of GPS coordinates (Requested for GPS Coordinates to be shown only to end users and uneditable)|
|Longitude|Equation to mirror answer in MoSDGPS_SQ002 **(blank answer in dataset if HF record is not yet updated, duplicate answer with MoSDGPS_SQ002 if HF record is updated)**||Needed variable for text display of GPS coordinates (Requested for GPS Coordinates to be shown only to end users and uneditable)|
|TEXTdisplayGPS| Text display of GPS Coordinates through Latitude & Longitude equations **(blank answer in dataset)**|| Text display of GPS coordinates to be shown only to end users and uneditable as requested|

**Text displays will not work using hidden questions (i.e., GEO3 and GEO6). Hence, hidden equations were created for the requested variables (to only be shown to end users / uneditable) to work (i.e., PoSDTEXT, TEXTdisplayGPS)

**Comment by JeffDotingco** [comment]
In addition, the number of columns in the dataset have already been reduced by 16. These 16 variables (HFName 1-16) were previous text displays of health facility names {MoSD2} requested as a questionnaire enhancement. This is already sorted out by putting the text displays in the description of question groups. Please see below:

<img width="1680" alt="Screen Shot 2020-05-20 at 11 27 33 PM" src="https://user-images.githubusercontent.com/50957748/82466665-48f57e00-9af3-11ea-9888-d9925c31ea35.png">

**Comment by JeffDotingco** [comment]
Already explained the reasons of having additional columns in the dataset.

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco it seems that still some field/columns have no significant use as per your table. So, could we please meet to discuss their use.

**Comment by JeffDotingco** [comment]
I can delete GEO3 and GEO6. Some hidden columns (GPS coordinates and Governorates and Districts) as requested by Yemen to be displayed only (uneditable) needs to come from equations as text displays (e.g, PoSDTEXT, TEXTdisplayGPS) will not work if it is coming from hidden columns, hence the need to use equation which are blank columns in the dataset. The significance of the additional columns are already stated in the table. Up to you and @Arafat and MoPHP, which columns to delete. But this will affect the appearance of the questionnaire.

**Comment by JeffDotingco** [comment]
I can delete GEO3 and GEO6. Some hidden columns (GPS coordinates and Governorates and Districts) as requested by Yemen to be displayed only (uneditable) needs to come from equations as text displays (e.g, PoSDTEXT, TEXTdisplayGPS) will not work if it is coming from hidden columns, hence the need to use equation which are blank columns in the dataset. The significance of the additional columns are already stated in the table. Up to you @MustafaAbdulrahmanWHO, Arafat and MoPHP, which columns to delete. But this will affect the appearance of the questionnaire.

**Comment by MustafaAbdulrahmanWHO** [comment]
@JeffDotingco Please be informed that in the case of Columns that are not essential and their only purpose is to be displayed only in the questionnaire (uneditable) such as GEO3, GEO6, GPS coordinates, etc. then such columns should be removed (except for "Health Facility Name in Arabic" field which is required to remind the enumerator what health facility he/she is currently updating).
